import { User } from "../payload-types";
import { ReadonlyRequestCookies } from "next/dist/server/web/spec-extension/adapters/request-cookies";
import { NextRequest } from "next/server"

export const getServerSideUser = async (
  cookies: NextRequest["cookies"] | ReadonlyRequestCookies
) => {
  const token = cookies.get("payload-token")?.value

  //this route is generated by the cms
  const currentlyLoggedInUser = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/users/me`, {
    headers: {
      //could also use BEARER <token>
      Authorization: `JWT ${token}`
    }
  })

  //user type or either null, if not logged in
  const {user} = (await currentlyLoggedInUser.json()) as {user: User | null}

  return {user}
};